modified:   install 	modified:   lib/install/micro.sh 	modified:   lib/install/nb.sh 	new file:   lib/visual/biosyntax

diff --git a/install b/install
--- a/install
+++ b/install
@@ -7,22 +7,63 @@ trap '' SIGINT SIGQUIT SIGTERM
 # ============================================================================= #
 XDG_CONFIG_HOME="${HOME}/.config"
 XDG_CACHE_HOME="${XDG_CACHE_HOME:=$HOME/.cache}"
+LOG_FILE="log.txt"
 # ============================================================================= #
+WARN() { echo "$@" |tee -a "$LOG_FILE"; }
 CHECK_LISTS() {
 [ ! -d "$XDG_CACHE_HOME"  ] && mkdir -p "$XDG_CACHE_HOME"
 [ ! -d "$XDG_CONFIG_HOME" ] && mkdir -p "$XDG_CONFIG_HOME"
 [ -z "$DOTFILES" ] && DOTFILES="$HOME/.dotfiles"
 [ -z "$TERM" ] && TERM='xterm-256color'
-[[ "$(command -v curl)" ]] || echo "Curl - missing" && sleep 2
-[[ "$(command -v python)" ]] || echo "Python - missing" && sleep 2
+[[ "$(command -v curl)" ]] || WARN "Curl - missing"
+[[ "$(command -v python)" ]] || WARN "Python - missing"
+[[ "$(command -v ruby)" ]] || WARN "Ruby - missing"
+[[ "$(command -v zsh)" ]] || WARN "Zsh - missing"
+[[ "$(command -v go)" ]] || WARN "Go - missing"
 }
-
+EXEC_LOG() {
+if [ -s "$LOG_FILE" ]; then
+tput setaf 1
+tput bold
+    echo "Seems dependencies are missing, auto installation not supported yet."
+tput setaf 1
+    echo "Installation may fail, proceed? [y/N]"
+tput setaf 3
+    cat "$LOG_FILE"
+tput sgr0
+    read -r response
+    case $response in
+    y|Y) rm "$LOG_FILE" && return ;;
+    n|N) rm "$LOG_FILE" && exit 0 ;;
+    *) rm "$LOG_FILE" && exit 0 ;;
+    esac
+fi
+}
 INSTALL() {
 CHECK_LISTS 
     "${DOTFILES}/bin/dosync" "--dosync" || exit 1
     exit 0
 }
+INTERACTIVE() {
+    CHECK_LISTS
+    EXEC_LOG
+    "${DOTFILES}/lib/install/install-fonts.sh"
+    "${DOTFILES}/lib/install/nb.sh"
+    "${DOTFILES}/lib/install/micro.sh" 
+    "${DOTFILES}/bin/dosync" "--dosync" || exit 1
+    exit 0
+}
+MAIN() {
+        while [ $# -gt 0 ]; do
+        case $1 in
+        --interactive) INTERACTIVE ;;
+        *)             INSTALL ;;
+        esac
+        shift
+    done
+}
+
 while true; do
-    INSTALL "${@}"
+    MAIN "${@}"
 done
-unset INSTALL
+unset MAIN
